name: Run script once an hour

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: is-a-dev/register
          path: main  

      - name: Run script
        uses: actions/setup-node@v2
        with:
          node-version: 16



      - name: Execute script
        run: |
          ls
          node index.js
          git add index.json
          git commit -m "Updated"
          git push
